### ISSUE TITLE
Проблема с путями

### ISSUE THREAD

**Issue by Michael-ShortCode** [alexsoin/gw-starter-kit#34]
После сборки проекта пути имеют следующий вид 
`<script type="module" crossorigin src="[/assets/js/focus-visible.js](https://github.com/assets/js/focus-visible.js)"></script>
<script type="module" crossorigin src="[/assets/js/index.js](https://github.com/assets/js/index.js)"></script>
<script type="module" crossorigin src="[/assets/js/short.js](https://github.com/assets/js/short.js)"></script>
<link rel="stylesheet" crossorigin href="[/assets/css/focus-visible.css](https://github.com/assets/css/focus-visible.css)">`

и эти файлы не доступны, если убрать /  в ручную по все работает корректно. Как можно пофиксить ?

**Comment by alexsoin** [comment]
странно как-то... не должно быть такого, можно по подробнее, какая ОС, какая версия nodejs, в консоле есть ли ошибки?

**Comment by Michael-ShortCode** [comment]
какая ОС - windows 10
nodejs v20.10.0
ошибок нет никаких все  нормально работает, но когда уже проект собрал полностью такая проблема с путями получается

**Comment by alexsoin** [comment]
Не получилось воспроизвести, после сборки всё без проблем собирается:

![изображение](https://github.com/user-attachments/assets/11f734c6-57c7-4f63-b7f2-f26d1fe00770)

Единственное могу предложить попробовать очистить проект от установленных модулей

```bash
rm -rf ./node_modules
```

Затем попробовать установку зависимостей через флаг:

```bash
npm install --legacy-peer-deps
```

Если это не поможет, то попробовать также удалить модули и установить через флаг force:

```bash
npm install --force
```

При работе в windows часто могут встречаться всякие необычные поведения, частично это исправляется использованием wsl в windows
