### ISSUE TITLE
Неработает в режиме реального времени

### ISSUE THREAD

**Issue by igor3310** [alexsoin/gw-starter-kit#4]
Здравствутйте!
1)пробовал команды:
npm run watch - сборка и запуск live-server в режиме developer
npm run prodwatch - сборка и запуск live-server в режиме production
и при изменении в файлах twig  и css непроисходит обновление в папке dist (обновляется только при команде из консоли) ?

2) При откртии БраузерСинк ощибка (Cannot GET /) , а самой страниц нет (да и не перезагружается при изменении файлов)?

3) Закоментировал ввод js  в фалах import.js и  base.js , а код откуда то берется и вставляется в dist main.js vendor.js - где отключить js?

**Comment by igor3310** [comment]
4) И большая вложенность css \dist\assets\css\src\assets\style\main.css

**Comment by alexsoin** [comment]
Развернул новую копию сборки, вот записал, что всё работает(подергивания - это изза программы, которой записывал):

![процесс автоперезагрузки](https://user-images.githubusercontent.com/3787132/102516154-fc354e00-40a7-11eb-81e9-cf431b9c6b99.gif)

Скорее всего проблемы по 1 и 2 пункту возникает изза особенности работы NodeJS в Windows системах. Я разработку в ней не виду, так что подсказать не смогу, как это поправить. Скорее всего надо пути в директориям в файле `gulpfile.js` править для ОС Windows.

По пункту 3 не совсем понял, где закоментировали ввод js. Файлы js обрабатываются через webpack и следовательно их отключать надо либо убрав совсем задачу из `gulpfile.js`, либо закоментировав не нужные точки входа в `webpack.config.js`:

![точки входа в webpack.config.js](https://user-images.githubusercontent.com/3787132/102517165-289d9a00-40a9-11eb-954f-01c60b81219f.png)

По 4 пункту не совсем пойму, что это за вложенность. Возможно также связано изза Windows. Должна быть вот такая структура каталога `dist`:

```
├── assets
│   ├── css
│   │   ├── main.css
│   │   └── main.min.css
│   ├── img
│   │   ├── gwst.png
│   │   └── rick.png
│   └── js
│       ├── main.min.js
│       └── vendor.min.js
└── index.html
```

Если найдёте решение и предлежения по решению для Windows (если у вас ошибка в этой ОС), то можете написать мне, либо прислать пуллреквест, я его с удовольствием приму. Думаю такие проблемы могли возникнуть не только у вас.

**Comment by igor3310** [comment]
По 3 пункту - когда коментирую эти строки - тогда с ощибкой останавливается сборка

**Comment by alexsoin** [comment]
>  По 3 пункту - когда коментирую эти строки - тогда с ощибкой останавливается сборка
и родной base.js не импортируется на дист

Когда мне например нужно чтобы vendor.js не собирался, я делаю вот так и всё собирается нормально:

![комментирование vendor](https://user-images.githubusercontent.com/3787132/102576065-27eb1f00-410e-11eb-98d1-2a79578b154d.png)

в данном примере какраз будут браться все файлы из директории `/src/assets/js/` (в том числе и base.js) и собираться в один файл main.min.js. Возможно у вас ошибка также была изза путей, в вебпаке свои пути приёма js файлов (строки 5-6 в файле webpack.config.js).

> П.С. Нафиг Вебпак нужен ?

Мне нравится как в нем работает изоляция кода и babel. У меня есть старая сборка без вебпака, и мне не удалось через галп настроить babel, чтобы он собирал js под ie10 (хотя я сильно не углублялся в данный вопрос, но с ходу так не получилось сделать), также мне не понравилось, что через галп js код получается не изолированным, а при навешивании всех мне нужных плагинов для галпа (gulp-uglify-es, gulp-minify и тд) у меня скорость сборки js заметно медленнее была, чем через вебпак.

> куда Вам сбросить?

pull request, либо любым удобным способом из [списка моих контактов](https://zencod.ru/about)

**Comment by igor3310** [comment]
Ясно спасибо - но у меня чет не хочет работать. а с ними какой то код добовляется

**Comment by alexsoin** [comment]
> И ФАЙЛЫ ИЗ /src/assets/js/ НЕ ДБОВЛЯЕТ

В файле `webpack.config.js` пути поправляли, чтобы работало для вашей ОС?

**Comment by igor3310** [comment]
Спасибо за сборку!
